### Dataset ###
data:
  name: custom
  folder: ../data/smd_nl

### Debug Evaluate ###
eval:
  n_samples: 1
  model_path: ""
  batch_size: 2
  num_workers: 0
  display_interval: 1
  device: cuda:0

  cache_folder: ./cache/smd_nl_debug
