### Dataset ###
data:
  name: custom
  folder: ../data/smd_nl

### Full Evaluate ###
eval:
  n_samples: 10
  model_path: ""
  batch_size: 16
  num_workers: 4
  display_interval: 1
  device: cuda:0

  cache_folder: ./cache/smd_nl_full
